name        : pulseaudio
version     : 6.0
release     : 16
source      :
    - http://freedesktop.org/software/pulseaudio/releases/pulseaudio-6.0.tar.xz : b50640e0b80b1607600accfad2e45aabb79d379bf6354c9671efa2065477f6f6
homepage    : http://www.freedesktop.org/wiki/Software/PulseAudio/
license     :
    - LGPL-2.1
summary     : Advanced sound system
component   : multimedia.audio
ccache      : no
builddeps   :
    - pkgconfig(alsa)
    - pkgconfig(sndfile)
    - pkgconfig(flac)
    - pkgconfig(json-c)
    - pkgconfig(speex)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(sbc)
    - pkgconfig(bluez)
    - pkgconfig(fftw3f)
    - pkgconfig(orc-0.4)
    - pkgconfig(x11-xcb)
    - pkgconfig(ice)
    - pkgconfig(sm)
    - pkgconfig(xtst)
    - libcap2-devel
description : |
    PulseAudio is a sound system for POSIX OSes, meaning that it is a proxy for your sound applications. It allows you to do advanced operations on your sound data as it passes between your application and your hardware. Things like transferring the audio to a different machine, changing the sample format or channel count and mixing several sounds into one are easily achieved using a sound server.
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-flat-volumes-as-they-re-making-folks-unhappy.patch
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    ./bootstrap.sh
    %configure --disable-static \
               --libexecdir=%libdir% \
               --enable-alsa \
               --disable-bluez4 \
               --enable-bluez5 \
               --enable-bluez5-native-headset \
               --enable-orc \
               --with-udev-rules-dir=/usr/lib/udev/rules.d \
               --enable-dbus
build      : |
    %make
install    : |
    %make_install -j1
    install -D -m 00644 $pkgfiles/pulseaudio.conf $installdir/%libdir%/sysusers.d/pulseaudio.conf
    # These incorrect files break gdm
    rm -rfv $installdir/etc/bash_completion.d
