name       : pulseaudio
version    : '15.0'
release    : 56
source     :
    - https://freedesktop.org/software/pulseaudio/releases/pulseaudio-15.0.tar.xz : a40b887a3ba98cc26976eb11bdb6613988f145b19024d1b6555c6a03c9cba1a0
homepage   : https://www.freedesktop.org/wiki/Software/PulseAudio/
license    : LGPL-2.1-or-later
component  :
    - multimedia.audio
    - equalizer : multimedia.audio
    - module-jack : multimedia.audio
    - module-jack-32bit : multimedia.audio
summary    :
    - Advanced sound system
    - equalizer : PulseAudio equalizer GUI (qpaeq)
    - module-jack : JACK modules for the PulseAudio sound server
    - module-jack-32bit : JACK modules for the PulseAudio sound server
description: |
    PulseAudio is a sound system for POSIX OSes, meaning that it is a proxy for your sound applications. It allows you to do advanced operations on your sound data as it passes between your application and your hardware. Things like transferring the audio to a different machine, changing the sample format or channel count and mixing several sounds into one are easily achieved using a sound server.
emul32     : yes
ccache     : no
libsplit   : no
optimize   : size
patterns   :
    - equalizer :
        - /usr/bin/qpaeq
        - /usr/lib64/pulse-*/modules/module-equalizer-sink.so
    - module-jack :
        - /usr/lib64/pulse-*/modules/module-jack*
    - module-jack-32bit :
        - /usr/lib32/pulse-*/modules/module-jack*
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(gtk+-3.0)
    - pkgconfig32(jack)
    - pkgconfig32(json-c)
    - pkgconfig32(libcap)
    - pkgconfig32(liblzma)
    - pkgconfig32(libudev)
    - pkgconfig32(orc-0.4)
    - pkgconfig32(sndfile)
    - pkgconfig32(sm)
    - pkgconfig32(speex)
    - pkgconfig32(soxr)
    - pkgconfig32(webrtc-audio-processing)
    - pkgconfig(avahi-core)
    - pkgconfig(bluez)
    - pkgconfig(check)
    - pkgconfig(fftw3f)
    - pkgconfig(sbc)
    - gdbm-32bit-devel
    - libtool-32bit-devel
    - openssl-11-32bit-devel
rundeps    :
    - rtkit
    - equalizer :
        - python3-dbus
        - python3-qt5
setup      : |
    %apply_patches

    if [[ ! -z "${EMUL32BUILD}" ]]; then
        extra_opts="-Davahi=disabled -Dbluez5=disabled -Dfftw=disabled -Dgtk=disabled -Dtests=false"
    else
        extra_opts="-Dbluez5=enabled -Dbluez5-native-headset=true -Dgsettings=enabled"
    fi
    %meson_configure \
        -Dalsa=enabled \
        -Ddatabase='gdbm' \
        -Ddbus=enabled \
        -Ddoxygen=false \
        -Dorc=enabled \
        -Dpulsedsp-location='%libdir%/pulseaudio' \
        -Dudevrulesdir=/usr/lib/udev/rules.d \
        $extra_opts
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -D -m 00644 $pkgfiles/pulseaudio.conf $installdir/%libdir%/sysusers.d/pulseaudio.conf
    # These incorrect files break gdm
    rm -rfv $installdir/usr/share/bash-completion
    # Ensure Audio works in PulseAudio
    ln -sv %libdir%/pulseaudio/libpulsecommon-${version}.so $installdir/%libdir%/.
