name       : pulseaudio
version    : 9.0
release    : 20
source     :
    - https://freedesktop.org/software/pulseaudio/releases/pulseaudio-9.0.tar.xz : c3d3d66b827f18fbe903fe3df647013f09fc1e2191c035be1ee2d82a9e404686
homepage   : http://www.freedesktop.org/wiki/Software/PulseAudio/
license    :
    - LGPL-2.1
summary    : Advanced sound system
component  : multimedia.audio
ccache     : no
libsplit   : no
optimize   : size
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(libudev)
    - pkgconfig(alsa)
    - pkgconfig32(alsa)
    - pkgconfig(sndfile)
    - pkgconfig32(sndfile)
    - pkgconfig(flac)
    - pkgconfig32(json-c)
    - pkgconfig(json-c)
    - pkgconfig(speex)
    - pkgconfig32(speex)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(sbc)
    - pkgconfig(bluez)
    - pkgconfig(fftw3f)
    - pkgconfig(orc-0.4)
    - pkgconfig32(orc-0.4)
    - pkgconfig(x11-xcb)
    - pkgconfig32(x11-xcb)
    - pkgconfig(ice)
    - pkgconfig32(ice)
    - pkgconfig(sm)
    - pkgconfig32(sm)
    - pkgconfig(xtst)
    - pkgconfig32(xtst)
    - pkgconfig32(liblzma)
    - pkgconfig32(libssl)
    - libcap2-devel
    - libcap2-32bit-devel
    - glibc-32bit-devel
    - libgcc-32bit
    - libtool-32bit-devel
    - libgcrypt-32bit-devel
    - dbus-32bit
emul32     : yes
description: |
    PulseAudio is a sound system for POSIX OSes, meaning that it is a proxy for your sound applications. It allows you to do advanced operations on your sound data as it passes between your application and your hardware. Things like transferring the audio to a different machine, changing the sample format or channel count and mixing several sounds into one are easily achieved using a sound server.
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-flat-volumes-as-they-re-making-folks-unhappy.patch
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    ./bootstrap.sh

    if [[ ! -z "${EMUL32BUILD}" ]]; then
        extra_opts="--disable-bluez5 --disable-gtk3 --without-fftw"
    else
        extra_opts="--enable-bluez5 --enable-bluez5-native-headset"
    fi

    %configure --prefix=/usr \
               --disable-static \
               --libexecdir=%libdir% \
               --enable-alsa \
               --disable-bluez4 \
               --enable-orc \
               --with-udev-rules-dir=/usr/lib/udev/rules.d \
               --enable-dbus \
               $extra_opts
build      : |
    %make
install    : |
    %make_install -j1
    install -D -m 00644 $pkgfiles/pulseaudio.conf $installdir/%libdir%/sysusers.d/pulseaudio.conf
    # These incorrect files break gdm
    rm -rfv $installdir/usr/share/bash-completion
    # Ensure Audio works in PulseAudio
    ln -sv %libdir%/pulseaudio/libpulsecommon-9.0.so $installdir/%libdir%/.

